import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, log_loss

# Assume your datasets are loaded into pandas DataFrames:
# df_matches, df_match_stats, df_teams, df_seasons

# Merge Matches with Match Statistics
df = pd.merge(df_matches, df_match_stats, left_on='id', right_on='match_id')

# Ensure chronological order (CRITICAL for rolling averages)
df['match_date'] = pd.to_datetime(df['match_date'])
df = df.sort_values('match_date').reset_index(drop=True)

# Create the Target Variable (0 = Away Win, 1 = Draw, 2 = Home Win)
conditions = [
    df['home_score'] > df['away_score'],
    df['home_score'] == df['away_score'],
    df['home_score'] < df['away_score']
]
choices = [2, 1, 0]
df['target'] = np.select(conditions, choices, default=np.nan)

# Melt the dataframe to team level
home_df = df[['id', 'match_date', 'home_team_id', 'home_score', 'away_score', 'home_xg', 'away_xg', 'home_ppda']].copy()
home_df.columns =['match_id', 'match_date', 'team_id', 'goals_for', 'goals_against', 'xg_for', 'xg_against', 'ppda']
home_df['is_home'] = 1

away_df = df[['id', 'match_date', 'away_team_id', 'away_score', 'home_score', 'away_xg', 'home_xg', 'away_ppda']].copy()
away_df.columns =['match_id', 'match_date', 'team_id', 'goals_for', 'goals_against', 'xg_for', 'xg_against', 'ppda']
away_df['is_home'] = 0

team_df = pd.concat([home_df, away_df]).sort_values(['team_id', 'match_date'])

# Calculate points won
def calc_points(gf, ga):
    if gf > ga: return 3
    elif gf == ga: return 1
    else: return 0
team_df['points'] = team_df.apply(lambda row: calc_points(row['goals_for'], row['goals_against']), axis=1)

# Shift by 1 so we don't include the current match in our rolling average!
team_df[['points_last_5', 'xg_for_last_5', 'xg_against_last_5', 'ppda_last_5']] = team_df.groupby('team_id')[['points', 'xg_for', 'xg_against', 'ppda']].transform(lambda x: x.shift(1).rolling(window=5, min_periods=1).mean())

# Separate back to Home and Away features to merge into the main df
home_features = team_df[team_df['is_home'] == 1][['match_id', 'points_last_5', 'xg_for_last_5', 'xg_against_last_5', 'ppda_last_5']]
home_features.columns =['id', 'home_points_l5', 'home_xg_for_l5', 'home_xg_against_l5', 'home_ppda_l5']

away_features = team_df[team_df['is_home'] == 0][['match_id', 'points_last_5', 'xg_for_last_5', 'xg_against_last_5', 'ppda_last_5']]
away_features.columns =['id', 'away_points_l5', 'away_xg_for_l5', 'away_xg_against_l5', 'away_ppda_l5']

# Merge back into main dataframe
df = pd.merge(df, home_features, on='id')
df = pd.merge(df, away_features, on='id')

# How much better is the home team's attacking xG than the away team's defending xG?
df['xg_diff'] = df['home_xg_for_l5'] - df['away_xg_for_l5']
df['form_diff'] = df['home_points_l5'] - df['away_points_l5']
df['pressing_diff'] = df['home_ppda_l5'] - df['away_ppda_l5']

# Drop NA values generated by early season rolling averages
model_df = df.dropna()

features =[
    'home_points_l5', 'away_points_l5', 'form_diff',
    'home_xg_for_l5', 'away_xg_for_l5', 'xg_diff',
    'home_xg_against_l5', 'away_xg_against_l5',
    'home_ppda_l5', 'away_ppda_l5', 'pressing_diff'
]

X = model_df[features]
y = model_df['target']

# Split chronologically (e.g., first 80% of matches for training, last 20% for testing)
split_idx = int(len(X) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

# Initialize XGBoost Classifier
clf = xgb.XGBClassifier(
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss',
    max_depth=4,
    learning_rate=0.05,
    n_estimators=200
)

# Train the model
clf.fit(X_train, y_train)

# Predict Probabilities
y_pred_proba = clf.predict_proba(X_test)
y_pred = clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")
print(f"Log Loss: {log_loss(y_test, y_pred_proba):.3f}")
