"""Infrastructure layer - cross-cutting concerns and shared utilities.

This module contains infrastructure code that is used across multiple features
but doesn't belong to any specific business feature.
"""

from algobet.infrastructure.config import (
    AlgobetConfig,
    get_config,
    reload_config,
    set_config,
)
from algobet.infrastructure.database import (
    async_init_db,
    async_session_scope,
    close_async_engine,
    create_async_db_engine,
    create_db_engine,
    get_async_session,
    get_db_url,
    get_session,
    get_shared_async_engine,
    init_db,
    session_scope,
)
from algobet.infrastructure.exceptions import (
    EXIT_CODES,
    AlgoBetError,
    ConfigFileNotFoundError,
    ConfigParseError,
    ConfigurationError,
    ConfigValidationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseMigrationError,
    DatabaseQueryError,
    DataError,
    DataExportError,
    DataImportError,
    DataNotFoundError,
    DataValidationError,
    InputValidationError,
    InsufficientDataError,
    ModelError,
    ModelLoadError,
    ModelNotFoundError,
    ModelSaveError,
    ModelValidationError,
    NoActiveModelError,
    ParameterValidationError,
    PredictionCalibrationError,
    PredictionError,
    PredictionFeatureError,
    PredictionValidationError,
    ScrapingBlockedError,
    ScrapingConnectionError,
    ScrapingError,
    ScrapingParseError,
    ScrapingTimeoutError,
    ServiceError,
    ServiceTimeoutError,
    ServiceUnavailableError,
    ValidationError,
    get_exit_code_description,
)
from algobet.infrastructure.logging_config import (
    get_logger,
    setup_logging,
)
from algobet.infrastructure.models import Base, TimestampMixin

__all__ = [
    # Config
    "AlgobetConfig",
    "get_config",
    "reload_config",
    "set_config",
    # Database
    "async_init_db",
    "async_session_scope",
    "close_async_engine",
    "create_async_db_engine",
    "create_db_engine",
    "get_async_session",
    "get_db_url",
    "get_session",
    "get_shared_async_engine",
    "init_db",
    "session_scope",
    # Exceptions
    "EXIT_CODES",
    "AlgoBetError",
    "ConfigFileNotFoundError",
    "ConfigParseError",
    "ConfigValidationError",
    "ConfigurationError",
    "DataError",
    "DataExportError",
    "DataImportError",
    "DataNotFoundError",
    "DataValidationError",
    "DatabaseConnectionError",
    "DatabaseError",
    "DatabaseMigrationError",
    "DatabaseQueryError",
    "InsufficientDataError",
    "InputValidationError",
    "ModelError",
    "ModelLoadError",
    "ModelNotFoundError",
    "ModelSaveError",
    "ModelValidationError",
    "NoActiveModelError",
    "ParameterValidationError",
    "PredictionCalibrationError",
    "PredictionError",
    "PredictionFeatureError",
    "PredictionValidationError",
    "ScrapingBlockedError",
    "ScrapingConnectionError",
    "ScrapingError",
    "ScrapingParseError",
    "ScrapingTimeoutError",
    "ServiceError",
    "ServiceTimeoutError",
    "ServiceUnavailableError",
    "ValidationError",
    "get_exit_code_description",
    # Logging
    "get_logger",
    "setup_logging",
    # Models
    "Base",
    "TimestampMixin",
]
